// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// Strings for Quick AI. Same contract as the other FeatureStrings structs:
/// memberwise init in declaration order, one static per language.
struct QuickAIFeatureStrings {
    let pageTitle: String
    let hubDescription: String
    let panelCaption: String
    let apiKeyLabel: String
    let apiKeyCaption: String
    let modelLabel: String
    let intensityLabel: String
    let intensityCaption: String
    let webSearchLabel: String
    let webSearchCaption: String
    let commandBarKeyLabel: String
    let commandBarKeyCaption: String
    let commandBarKeyTab: String
    let commandBarKeyGrave: String
    let commandBarKeySlash: String
    let privacyCaption: String
    let askPlaceholder: String
    let generating: String
    let send: String
    let keepChat: String
    let openChats: String
    let newChat: String
    let savedChats: String
    let emptyChats: String
    let deleteChat: String
    let copyResult: String
    let webSearchOn: String
    let webSearchOff: String
    let attachedContext: String
    let noKey: String
    let errorNetwork: String
    let errorEmpty: String
    let errorParse: String
    let errorNoKey: String
    let testConnection: String
    let testSuccess: String
    let testFailed: String
    let followUpHint: String
    let completeWithShiftTab: String
}

extension FeatureStrings {
    static func quickAI(_ language: AppLanguage) -> QuickAIFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension QuickAIFeatureStrings {
    static let enUS = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "Chat with OpenAI from the Command Bar, with your own API key, saved chats and optional web search",
        panelCaption: "Open a saved chat, or start a new one.",
        apiKeyLabel: "OpenAI API key",
        apiKeyCaption: "Your key stays on this Mac, owner-only, and is never part of a settings backup. The prompt is sent to OpenAI only when you press Return.",
        modelLabel: "Model",
        intensityLabel: "Intensity",
        intensityCaption: "How hard the model thinks before answering. Higher means slower and usually better. Only GPT-5.6 models use this.",
        webSearchLabel: "Web search",
        webSearchCaption: "Lets the model look up current facts. Uses OpenAI web search and still sends only what you type.",
        commandBarKeyLabel: "Command Bar key",
        commandBarKeyCaption: "While the Command Bar is open, this key switches it into Quick AI. Shift-Tab still completes the selected row.",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "Grave accent (`)",
        commandBarKeySlash: "Slash (/)",
        privacyCaption: "Quick AI is off until you install it. Nothing is sent in the background. Chats are stored locally on this Mac.",
        askPlaceholder: "Ask anything",
        generating: "Thinking",
        send: "Send",
        keepChat: "Keep chat",
        openChats: "Open chats",
        newChat: "New chat",
        savedChats: "Saved chats",
        emptyChats: "No saved chats yet.",
        deleteChat: "Delete chat",
        copyResult: "Copy",
        webSearchOn: "Search on",
        webSearchOff: "Search off",
        attachedContext: "Using selected text",
        noKey: "Add your OpenAI API key in Settings.",
        errorNetwork: "OpenAI did not answer. Check the key and the connection.",
        errorEmpty: "The model returned nothing.",
        errorParse: "The reply could not be read.",
        errorNoKey: "This key was refused. Check it in Settings.",
        testConnection: "Test connection",
        testSuccess: "OpenAI answered.",
        testFailed: "OpenAI did not answer.",
        followUpHint: "Return to ask a follow-up. Esc leaves Quick AI.",
        completeWithShiftTab: "Shift-Tab"
    )

    static let de = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "Mit OpenAI aus der Befehlsleiste chatten, mit eigenem API-Schlüssel, gespeicherten Chats und optionaler Websuche",
        panelCaption: "Einen gespeicherten Chat öffnen oder einen neuen starten.",
        apiKeyLabel: "OpenAI-API-Schlüssel",
        apiKeyCaption: "Dein Schlüssel bleibt auf diesem Mac, nur für dich lesbar, und ist nie Teil eines Einstellungs-Backups. Der Prompt geht erst an OpenAI, wenn du Return drückst.",
        modelLabel: "Modell",
        intensityLabel: "Intensität",
        intensityCaption: "Wie gründlich das Modell nachdenkt. Höher ist langsamer und meist besser. Nur GPT-5.6-Modelle nutzen das.",
        webSearchLabel: "Websuche",
        webSearchCaption: "Damit kann das Modell aktuelle Fakten nachschlagen. Nutzt die OpenAI-Websuche und sendet weiterhin nur, was du tippst.",
        commandBarKeyLabel: "Taste in der Befehlsleiste",
        commandBarKeyCaption: "Solange die Befehlsleiste offen ist, wechselt diese Taste zu Quick AI. Umschalt-Tab vervollständigt weiterhin die ausgewählte Zeile.",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "Akzent (`)",
        commandBarKeySlash: "Schrägstrich (/)",
        privacyCaption: "Quick AI bleibt aus, bis du es installierst. Im Hintergrund wird nichts gesendet. Chats liegen lokal auf diesem Mac.",
        askPlaceholder: "Frag irgendwas",
        generating: "Denkt nach",
        send: "Senden",
        keepChat: "Chat behalten",
        openChats: "Chats öffnen",
        newChat: "Neuer Chat",
        savedChats: "Gespeicherte Chats",
        emptyChats: "Noch keine gespeicherten Chats.",
        deleteChat: "Chat löschen",
        copyResult: "Kopieren",
        webSearchOn: "Suche an",
        webSearchOff: "Suche aus",
        attachedContext: "Markierter Text wird mitgeschickt",
        noKey: "Lege deinen OpenAI-API-Schlüssel in den Einstellungen ab.",
        errorNetwork: "OpenAI hat nicht geantwortet. Prüfe den Schlüssel und die Verbindung.",
        errorEmpty: "Das Modell hat nichts zurückgegeben.",
        errorParse: "Die Antwort konnte nicht gelesen werden.",
        errorNoKey: "Dieser Schlüssel wurde abgelehnt. Prüfe ihn in den Einstellungen.",
        testConnection: "Verbindung testen",
        testSuccess: "OpenAI hat geantwortet.",
        testFailed: "OpenAI hat nicht geantwortet.",
        followUpHint: "Return stellt eine Nachfrage. Esc verlässt Quick AI.",
        completeWithShiftTab: "Umschalt-Tab"
    )

    static let ptBR = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "Converse com a OpenAI pela Barra de Comandos, com a sua chave de API, chats salvos e busca na web opcional",
        panelCaption: "Abra um chat salvo, ou comece um novo.",
        apiKeyLabel: "Chave de API da OpenAI",
        apiKeyCaption: "A chave fica neste Mac, só para você, e nunca entra num backup de ajustes. O prompt só vai à OpenAI quando você pressiona Return.",
        modelLabel: "Modelo",
        intensityLabel: "Intensidade",
        intensityCaption: "Quanto o modelo pensa antes de responder. Mais alto é mais lento e geralmente melhor. Só os modelos GPT-5.6 usam isso.",
        webSearchLabel: "Busca na web",
        webSearchCaption: "Permite que o modelo busque fatos atuais. Usa a busca da OpenAI e ainda envia só o que você digita.",
        commandBarKeyLabel: "Tecla da Barra de Comandos",
        commandBarKeyCaption: "Com a Barra de Comandos aberta, esta tecla entra no Quick AI. Shift-Tab ainda completa a linha selecionada.",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "Acento grave (`)",
        commandBarKeySlash: "Barra (/)",
        privacyCaption: "O Quick AI fica desligado até você instalá-lo. Nada é enviado em segundo plano. Os chats ficam neste Mac.",
        askPlaceholder: "Pergunte qualquer coisa",
        generating: "Pensando",
        send: "Enviar",
        keepChat: "Guardar chat",
        openChats: "Abrir chats",
        newChat: "Novo chat",
        savedChats: "Chats salvos",
        emptyChats: "Nenhum chat salvo ainda.",
        deleteChat: "Apagar chat",
        copyResult: "Copiar",
        webSearchOn: "Busca ligada",
        webSearchOff: "Busca desligada",
        attachedContext: "Usando o texto selecionado",
        noKey: "Adicione sua chave de API da OpenAI em Ajustes.",
        errorNetwork: "A OpenAI não respondeu. Verifique a chave e a conexão.",
        errorEmpty: "O modelo não devolveu nada.",
        errorParse: "A resposta não pôde ser lida.",
        errorNoKey: "Esta chave foi recusada. Verifique-a em Ajustes.",
        testConnection: "Testar conexão",
        testSuccess: "A OpenAI respondeu.",
        testFailed: "A OpenAI não respondeu.",
        followUpHint: "Return faz uma pergunta seguinte. Esc sai do Quick AI.",
        completeWithShiftTab: "Shift-Tab"
    )

    static let tr = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "Kendi API anahtarınla Komut Çubuğundan OpenAI ile sohbet et, sohbetleri kaydet, isteğe bağlı web araması kullan",
        panelCaption: "Kayıtlı bir sohbet aç veya yeni bir tane başlat.",
        apiKeyLabel: "OpenAI API anahtarı",
        apiKeyCaption: "Anahtarın bu Mac’te, yalnızca sana açık kalır ve ayar yedeğine asla girmez. İstem yalnız Return’e basınca OpenAI’ye gider.",
        modelLabel: "Model",
        intensityLabel: "Yoğunluk",
        intensityCaption: "Modelin cevap vermeden önce ne kadar düşüneceği. Daha yüksek daha yavaş ve genelde daha iyi. Yalnızca GPT-5.6 modelleri kullanır.",
        webSearchLabel: "Web araması",
        webSearchCaption: "Modelin güncel gerçekleri aramasına izin verir. OpenAI web aramasını kullanır ve yine yalnızca yazdığını gönderir.",
        commandBarKeyLabel: "Komut Çubuğu tuşu",
        commandBarKeyCaption: "Komut Çubuğu açıkken bu tuş Quick AI’ye geçer. Shift-Tab hâlâ seçili satırı tamamlar.",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "Aksan (`)",
        commandBarKeySlash: "Eğik çizgi (/)",
        privacyCaption: "Quick AI, sen kurana kadar kapalıdır. Arka planda hiçbir şey gönderilmez. Sohbetler bu Mac’te durur.",
        askPlaceholder: "Bir şey sor",
        generating: "Düşünüyor",
        send: "Gönder",
        keepChat: "Sohbeti sakla",
        openChats: "Sohbetleri aç",
        newChat: "Yeni sohbet",
        savedChats: "Kayıtlı sohbetler",
        emptyChats: "Henüz kayıtlı sohbet yok.",
        deleteChat: "Sohbeti sil",
        copyResult: "Kopyala",
        webSearchOn: "Arama açık",
        webSearchOff: "Arama kapalı",
        attachedContext: "Seçili metin kullanılıyor",
        noKey: "OpenAI API anahtarını Ayarlar’a ekle.",
        errorNetwork: "OpenAI yanıt vermedi. Anahtarı ve bağlantıyı kontrol et.",
        errorEmpty: "Model hiçbir şey döndürmedi.",
        errorParse: "Yanıt okunamadı.",
        errorNoKey: "Bu anahtar reddedildi. Ayarlar’dan kontrol et.",
        testConnection: "Bağlantıyı dene",
        testSuccess: "OpenAI yanıt verdi.",
        testFailed: "OpenAI yanıt vermedi.",
        followUpHint: "Return takip sorusu sorar. Esc Quick AI’den çıkar.",
        completeWithShiftTab: "Shift-Tab"
    )

    static let ru = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "Общайтесь с OpenAI из панели команд со своим ключом API, сохранёнными чатами и поиском в сети",
        panelCaption: "Откройте сохранённый чат или начните новый.",
        apiKeyLabel: "Ключ API OpenAI",
        apiKeyCaption: "Ключ остаётся на этом Mac, только для вас, и никогда не входит в резервную копию настроек. Запрос уходит в OpenAI только после Return.",
        modelLabel: "Модель",
        intensityLabel: "Интенсивность",
        intensityCaption: "Насколько тщательно модель думает перед ответом. Выше значит медленнее и обычно лучше. Только модели GPT-5.6.",
        webSearchLabel: "Поиск в сети",
        webSearchCaption: "Позволяет модели искать актуальные факты. Использует поиск OpenAI и по-прежнему отправляет только то, что вы печатаете.",
        commandBarKeyLabel: "Клавиша панели команд",
        commandBarKeyCaption: "Пока панель команд открыта, эта клавиша включает Quick AI. Shift-Tab по-прежнему дополняет выбранную строку.",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "Апостроф (`)",
        commandBarKeySlash: "Слэш (/)",
        privacyCaption: "Quick AI выключен, пока вы его не установите. В фоне ничего не отправляется. Чаты хранятся на этом Mac.",
        askPlaceholder: "Спросите что угодно",
        generating: "Думает",
        send: "Отправить",
        keepChat: "Сохранить чат",
        openChats: "Открыть чаты",
        newChat: "Новый чат",
        savedChats: "Сохранённые чаты",
        emptyChats: "Пока нет сохранённых чатов.",
        deleteChat: "Удалить чат",
        copyResult: "Скопировать",
        webSearchOn: "Поиск включён",
        webSearchOff: "Поиск выключен",
        attachedContext: "Используется выделенный текст",
        noKey: "Добавьте ключ API OpenAI в Настройках.",
        errorNetwork: "OpenAI не ответил. Проверьте ключ и соединение.",
        errorEmpty: "Модель ничего не вернула.",
        errorParse: "Ответ не удалось прочитать.",
        errorNoKey: "Этот ключ отклонён. Проверьте его в Настройках.",
        testConnection: "Проверить соединение",
        testSuccess: "OpenAI ответил.",
        testFailed: "OpenAI не ответил.",
        followUpHint: "Return задаёт уточнение. Esc выходит из Quick AI.",
        completeWithShiftTab: "Shift-Tab"
    )

    static let es = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "Habla con OpenAI desde la Barra de Comandos, con tu propia clave de API, chats guardados y búsqueda web opcional",
        panelCaption: "Abre un chat guardado o empieza uno nuevo.",
        apiKeyLabel: "Clave de API de OpenAI",
        apiKeyCaption: "La clave se queda en este Mac, solo para ti, y nunca entra en una copia de ajustes. El prompt solo se envía a OpenAI cuando pulsas Return.",
        modelLabel: "Modelo",
        intensityLabel: "Intensidad",
        intensityCaption: "Cuánto piensa el modelo antes de responder. Más alto es más lento y suele ser mejor. Solo los modelos GPT-5.6 lo usan.",
        webSearchLabel: "Búsqueda web",
        webSearchCaption: "Permite que el modelo consulte hechos actuales. Usa la búsqueda de OpenAI y sigue enviando solo lo que escribes.",
        commandBarKeyLabel: "Tecla de la Barra de Comandos",
        commandBarKeyCaption: "Con la Barra de Comandos abierta, esta tecla entra en Quick AI. Mayús-Tab sigue completando la fila seleccionada.",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "Acento grave (`)",
        commandBarKeySlash: "Barra (/)",
        privacyCaption: "Quick AI está apagado hasta que lo instales. No se envía nada en segundo plano. Los chats se quedan en este Mac.",
        askPlaceholder: "Pregunta lo que sea",
        generating: "Pensando",
        send: "Enviar",
        keepChat: "Conservar chat",
        openChats: "Abrir chats",
        newChat: "Chat nuevo",
        savedChats: "Chats guardados",
        emptyChats: "Aún no hay chats guardados.",
        deleteChat: "Eliminar chat",
        copyResult: "Copiar",
        webSearchOn: "Búsqueda on",
        webSearchOff: "Búsqueda off",
        attachedContext: "Usando el texto seleccionado",
        noKey: "Añade tu clave de API de OpenAI en Ajustes.",
        errorNetwork: "OpenAI no respondió. Comprueba la clave y la conexión.",
        errorEmpty: "El modelo no devolvió nada.",
        errorParse: "No se pudo leer la respuesta.",
        errorNoKey: "Esta clave fue rechazada. Compruébala en Ajustes.",
        testConnection: "Probar conexión",
        testSuccess: "OpenAI respondió.",
        testFailed: "OpenAI no respondió.",
        followUpHint: "Return hace una pregunta siguiente. Esc sale de Quick AI.",
        completeWithShiftTab: "Mayús-Tab"
    )

    static let fr = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "Discutez avec OpenAI depuis la Barre de Commandes, avec votre clé d'API, des chats enregistrés et une recherche web optionnelle",
        panelCaption: "Ouvrez un chat enregistré, ou commencez-en un nouveau.",
        apiKeyLabel: "Clé d'API OpenAI",
        apiKeyCaption: "Votre clé reste sur ce Mac, pour vous seul, et n'entre jamais dans une sauvegarde des réglages. Le prompt n'est envoyé à OpenAI que lorsque vous appuyez sur Retour.",
        modelLabel: "Modèle",
        intensityLabel: "Intensité",
        intensityCaption: "À quel point le modèle réfléchit avant de répondre. Plus haut signifie plus lent et souvent mieux. Seuls les modèles GPT-5.6 l'utilisent.",
        webSearchLabel: "Recherche web",
        webSearchCaption: "Permet au modèle de vérifier des faits actuels. Utilise la recherche OpenAI et n'envoie toujours que ce que vous tapez.",
        commandBarKeyLabel: "Touche de la Barre de Commandes",
        commandBarKeyCaption: "Tant que la Barre de Commandes est ouverte, cette touche passe en Quick AI. Maj-Tab complète toujours la ligne sélectionnée.",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "Accent grave (`)",
        commandBarKeySlash: "Slash (/)",
        privacyCaption: "Quick AI reste éteint tant que vous ne l'installez pas. Rien n'est envoyé en arrière-plan. Les chats restent sur ce Mac.",
        askPlaceholder: "Demandez n'importe quoi",
        generating: "Réflexion",
        send: "Envoyer",
        keepChat: "Garder le chat",
        openChats: "Ouvrir les chats",
        newChat: "Nouveau chat",
        savedChats: "Chats enregistrés",
        emptyChats: "Aucun chat enregistré pour l'instant.",
        deleteChat: "Supprimer le chat",
        copyResult: "Copier",
        webSearchOn: "Recherche activée",
        webSearchOff: "Recherche désactivée",
        attachedContext: "Texte sélectionné inclus",
        noKey: "Ajoutez votre clé d'API OpenAI dans les Réglages.",
        errorNetwork: "OpenAI n'a pas répondu. Vérifiez la clé et la connexion.",
        errorEmpty: "Le modèle n'a rien renvoyé.",
        errorParse: "La réponse n'a pas pu être lue.",
        errorNoKey: "Cette clé a été refusée. Vérifiez-la dans les Réglages.",
        testConnection: "Tester la connexion",
        testSuccess: "OpenAI a répondu.",
        testFailed: "OpenAI n'a pas répondu.",
        followUpHint: "Retour pose une question de suivi. Esc quitte Quick AI.",
        completeWithShiftTab: "Maj-Tab"
    )

    static let it = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "Chatta con OpenAI dalla Barra dei Comandi, con la tua chiave API, chat salvate e ricerca web facoltativa",
        panelCaption: "Apri una chat salvata, o iniziane una nuova.",
        apiKeyLabel: "Chiave API OpenAI",
        apiKeyCaption: "La chiave resta su questo Mac, solo per te, e non entra mai in un backup delle impostazioni. Il prompt va a OpenAI solo quando premi Invio.",
        modelLabel: "Modello",
        intensityLabel: "Intensità",
        intensityCaption: "Quanto il modello riflette prima di rispondere. Più alto è più lento e di solito meglio. Solo i modelli GPT-5.6 lo usano.",
        webSearchLabel: "Ricerca web",
        webSearchCaption: "Permette al modello di cercare fatti aggiornati. Usa la ricerca OpenAI e invia comunque solo ciò che scrivi.",
        commandBarKeyLabel: "Tasto della Barra dei Comandi",
        commandBarKeyCaption: "Con la Barra dei Comandi aperta, questo tasto entra in Quick AI. Maiusc-Tab completa ancora la riga selezionata.",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "Accento grave (`)",
        commandBarKeySlash: "Slash (/)",
        privacyCaption: "Quick AI resta spento finché non lo installi. In background non viene inviato nulla. Le chat restano su questo Mac.",
        askPlaceholder: "Chiedi qualsiasi cosa",
        generating: "Sto pensando",
        send: "Invia",
        keepChat: "Tieni la chat",
        openChats: "Apri le chat",
        newChat: "Nuova chat",
        savedChats: "Chat salvate",
        emptyChats: "Nessuna chat salvata.",
        deleteChat: "Elimina chat",
        copyResult: "Copia",
        webSearchOn: "Ricerca on",
        webSearchOff: "Ricerca off",
        attachedContext: "Uso del testo selezionato",
        noKey: "Aggiungi la chiave API OpenAI nelle Impostazioni.",
        errorNetwork: "OpenAI non ha risposto. Controlla la chiave e la connessione.",
        errorEmpty: "Il modello non ha restituito nulla.",
        errorParse: "La risposta non è stata letta.",
        errorNoKey: "Questa chiave è stata rifiutata. Controllala nelle Impostazioni.",
        testConnection: "Prova la connessione",
        testSuccess: "OpenAI ha risposto.",
        testFailed: "OpenAI non ha risposto.",
        followUpHint: "Invio fa una domanda di seguito. Esc esce da Quick AI.",
        completeWithShiftTab: "Maiusc-Tab"
    )

    static let ja = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "自分のAPIキーでコマンドバーからOpenAIと会話し、チャットを保存し、必要ならウェブ検索も使えます",
        panelCaption: "保存したチャットを開くか、新しく始めます。",
        apiKeyLabel: "OpenAI APIキー",
        apiKeyCaption: "キーはこのMacにだけ、あなた専用で保存され、設定のバックアップには入りません。Returnを押したときだけプロンプトがOpenAIに送られます。",
        modelLabel: "モデル",
        intensityLabel: "強度",
        intensityCaption: "回答前にどのくらい考えるか。高いほど遅く、多くの場合より良い結果になります。GPT-5.6モデルのみ。",
        webSearchLabel: "ウェブ検索",
        webSearchCaption: "モデルが最新の事実を調べられるようにします。OpenAIのウェブ検索を使い、送るのは入力した内容だけです。",
        commandBarKeyLabel: "コマンドバーのキー",
        commandBarKeyCaption: "コマンドバーを開いているあいだ、このキーでQuick AIに切り替わります。Shift-Tabはこれまで通り選択中の行を補完します。",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "アクサン (`)",
        commandBarKeySlash: "スラッシュ (/)",
        privacyCaption: "Quick AIはインストールするまでオフです。バックグラウンドでは何も送りません。チャットはこのMacに残ります。",
        askPlaceholder: "何でも聞いてください",
        generating: "考え中",
        send: "送信",
        keepChat: "チャットを残す",
        openChats: "チャットを開く",
        newChat: "新しいチャット",
        savedChats: "保存したチャット",
        emptyChats: "まだ保存したチャットはありません。",
        deleteChat: "チャットを削除",
        copyResult: "コピー",
        webSearchOn: "検索オン",
        webSearchOff: "検索オフ",
        attachedContext: "選択中のテキストを使用",
        noKey: "設定にOpenAI APIキーを追加してください。",
        errorNetwork: "OpenAIが応答しませんでした。キーと接続を確認してください。",
        errorEmpty: "モデルは何も返しませんでした。",
        errorParse: "返信を読み取れませんでした。",
        errorNoKey: "このキーは拒否されました。設定で確認してください。",
        testConnection: "接続をテスト",
        testSuccess: "OpenAIが応答しました。",
        testFailed: "OpenAIは応答しませんでした。",
        followUpHint: "Returnで続きを質問します。EscでQuick AIを終了します。",
        completeWithShiftTab: "Shift-Tab"
    )

    static let ko = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "내 API 키로 명령 막대에서 OpenAI와 대화하고, 채팅을 저장하고, 원하면 웹 검색도 사용합니다",
        panelCaption: "저장한 채팅을 열거나 새로 시작합니다.",
        apiKeyLabel: "OpenAI API 키",
        apiKeyCaption: "키는 이 Mac에만, 본인만 읽을 수 있게 저장되며 설정 백업에는 절대 들어가지 않습니다. Return을 누를 때만 프롬프트가 OpenAI로 전송됩니다.",
        modelLabel: "모델",
        intensityLabel: "강도",
        intensityCaption: "답하기 전에 모델이 얼마나 깊이 생각할지. 높을수록 느리고 보통 더 좋습니다. GPT-5.6 모델만 사용합니다.",
        webSearchLabel: "웹 검색",
        webSearchCaption: "모델이 최신 사실을 찾아볼 수 있게 합니다. OpenAI 웹 검색을 쓰며, 보내는 것은 입력한 내용뿐입니다.",
        commandBarKeyLabel: "명령 막대 키",
        commandBarKeyCaption: "명령 막대가 열려 있는 동안 이 키로 Quick AI로 전환합니다. Shift-Tab은 선택한 행을 그대로 완성합니다.",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "억음 부호 (`)",
        commandBarKeySlash: "슬래시 (/)",
        privacyCaption: "Quick AI는 설치하기 전까지 꺼져 있습니다. 백그라운드에서는 아무것도 보내지 않습니다. 채팅은 이 Mac에 남습니다.",
        askPlaceholder: "무엇이든 물어보세요",
        generating: "생각 중",
        send: "보내기",
        keepChat: "채팅 유지",
        openChats: "채팅 열기",
        newChat: "새 채팅",
        savedChats: "저장한 채팅",
        emptyChats: "아직 저장한 채팅이 없습니다.",
        deleteChat: "채팅 삭제",
        copyResult: "복사",
        webSearchOn: "검색 켜짐",
        webSearchOff: "검색 꺼짐",
        attachedContext: "선택한 텍스트 사용",
        noKey: "설정에 OpenAI API 키를 추가하세요.",
        errorNetwork: "OpenAI가 응답하지 않았습니다. 키와 연결을 확인하세요.",
        errorEmpty: "모델이 아무것도 반환하지 않았습니다.",
        errorParse: "답변을 읽을 수 없습니다.",
        errorNoKey: "이 키는 거부되었습니다. 설정에서 확인하세요.",
        testConnection: "연결 테스트",
        testSuccess: "OpenAI가 응답했습니다.",
        testFailed: "OpenAI가 응답하지 않았습니다.",
        followUpHint: "Return으로 후속 질문을 합니다. Esc는 Quick AI를 종료합니다.",
        completeWithShiftTab: "Shift-Tab"
    )

    static let zhHans = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "用你自己的 API 密钥从命令栏与 OpenAI 对话，可保存聊天，也可选用网页搜索",
        panelCaption: "打开已保存的聊天，或开始新的对话。",
        apiKeyLabel: "OpenAI API 密钥",
        apiKeyCaption: "密钥只留在这台 Mac 上、仅你可读，并且永远不会进入设置备份。只有按下 Return 时才会把内容发给 OpenAI。",
        modelLabel: "模型",
        intensityLabel: "强度",
        intensityCaption: "模型在回答前思考的程度。越高越慢，通常更好。仅 GPT-5.6 模型使用。",
        webSearchLabel: "网页搜索",
        webSearchCaption: "让模型查找当前事实。使用 OpenAI 网页搜索，发送的仍然只有你输入的内容。",
        commandBarKeyLabel: "命令栏按键",
        commandBarKeyCaption: "命令栏打开时，这个按键进入 Quick AI。Shift-Tab 仍然补全所选行。",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "重音符 (`)",
        commandBarKeySlash: "斜杠 (/)",
        privacyCaption: "在你安装之前，Quick AI 是关闭的。后台不会发送任何内容。聊天保存在这台 Mac 上。",
        askPlaceholder: "随便问",
        generating: "思考中",
        send: "发送",
        keepChat: "保留聊天",
        openChats: "打开聊天",
        newChat: "新聊天",
        savedChats: "已保存的聊天",
        emptyChats: "还没有保存的聊天。",
        deleteChat: "删除聊天",
        copyResult: "拷贝",
        webSearchOn: "搜索开",
        webSearchOff: "搜索关",
        attachedContext: "正在使用所选文本",
        noKey: "请在设置中添加 OpenAI API 密钥。",
        errorNetwork: "OpenAI 没有回应。请检查密钥和网络。",
        errorEmpty: "模型没有返回内容。",
        errorParse: "无法读取回复。",
        errorNoKey: "此密钥被拒绝。请在设置中检查。",
        testConnection: "测试连接",
        testSuccess: "OpenAI 已回应。",
        testFailed: "OpenAI 没有回应。",
        followUpHint: "Return 继续提问。Esc 离开 Quick AI。",
        completeWithShiftTab: "Shift-Tab"
    )

    static let zhTW = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "用你自己的 API 金鑰從指令列與 OpenAI 對話，可儲存聊天，也可選用網頁搜尋",
        panelCaption: "開啟已儲存的聊天，或開始新的對話。",
        apiKeyLabel: "OpenAI API 金鑰",
        apiKeyCaption: "金鑰只留在這台 Mac 上、僅你可讀，並且永遠不會進入設定備份。只有按下 Return 時才會把內容傳給 OpenAI。",
        modelLabel: "模型",
        intensityLabel: "強度",
        intensityCaption: "模型在回答前思考的程度。越高越慢，通常更好。僅 GPT-5.6 模型使用。",
        webSearchLabel: "網頁搜尋",
        webSearchCaption: "讓模型查找當前事實。使用 OpenAI 網頁搜尋，傳送的仍然只有你輸入的內容。",
        commandBarKeyLabel: "指令列按鍵",
        commandBarKeyCaption: "指令列開啟時，這個按鍵進入 Quick AI。Shift-Tab 仍然補全所選列。",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "重音符 (`)",
        commandBarKeySlash: "斜線 (/)",
        privacyCaption: "在你安裝之前，Quick AI 是關閉的。背景不會傳送任何內容。聊天保存在這台 Mac 上。",
        askPlaceholder: "隨便問",
        generating: "思考中",
        send: "傳送",
        keepChat: "保留聊天",
        openChats: "開啟聊天",
        newChat: "新聊天",
        savedChats: "已儲存的聊天",
        emptyChats: "還沒有儲存的聊天。",
        deleteChat: "刪除聊天",
        copyResult: "拷貝",
        webSearchOn: "搜尋開",
        webSearchOff: "搜尋關",
        attachedContext: "正在使用所選文字",
        noKey: "請在設定中加入 OpenAI API 金鑰。",
        errorNetwork: "OpenAI 沒有回應。請檢查金鑰和網路。",
        errorEmpty: "模型沒有傳回內容。",
        errorParse: "無法讀取回覆。",
        errorNoKey: "此金鑰被拒絕。請在設定中檢查。",
        testConnection: "測試連線",
        testSuccess: "OpenAI 已回應。",
        testFailed: "OpenAI 沒有回應。",
        followUpHint: "Return 繼續提問。Esc 離開 Quick AI。",
        completeWithShiftTab: "Shift-Tab"
    )

    static let zhHK = QuickAIFeatureStrings(
        pageTitle: "Quick AI",
        hubDescription: "用你自己的 API 密鑰從指令列與 OpenAI 對話，可儲存聊天，也可選用網頁搜尋",
        panelCaption: "開啟已儲存的聊天，或開始新的對話。",
        apiKeyLabel: "OpenAI API 密鑰",
        apiKeyCaption: "密鑰只留在這部 Mac 上、僅你可讀，並且永遠不會進入設定備份。只有按下 Return 時才會把內容傳給 OpenAI。",
        modelLabel: "模型",
        intensityLabel: "強度",
        intensityCaption: "模型在回答前思考的程度。越高越慢，通常更好。僅 GPT-5.6 模型使用。",
        webSearchLabel: "網頁搜尋",
        webSearchCaption: "讓模型查找當前事實。使用 OpenAI 網頁搜尋，傳送的仍然只有你輸入的內容。",
        commandBarKeyLabel: "指令列按鍵",
        commandBarKeyCaption: "指令列開啟時，這個按鍵進入 Quick AI。Shift-Tab 仍然補全所選列。",
        commandBarKeyTab: "Tab",
        commandBarKeyGrave: "重音符 (`)",
        commandBarKeySlash: "斜線 (/)",
        privacyCaption: "在你安裝之前，Quick AI 是關閉的。背景不會傳送任何內容。聊天保存在這部 Mac 上。",
        askPlaceholder: "隨便問",
        generating: "思考中",
        send: "傳送",
        keepChat: "保留聊天",
        openChats: "開啟聊天",
        newChat: "新聊天",
        savedChats: "已儲存的聊天",
        emptyChats: "還沒有儲存的聊天。",
        deleteChat: "刪除聊天",
        copyResult: "複製",
        webSearchOn: "搜尋開",
        webSearchOff: "搜尋關",
        attachedContext: "正在使用所選文字",
        noKey: "請在設定中加入 OpenAI API 密鑰。",
        errorNetwork: "OpenAI 沒有回應。請檢查密鑰和網絡。",
        errorEmpty: "模型沒有傳回內容。",
        errorParse: "無法讀取回覆。",
        errorNoKey: "此密鑰被拒絕。請在設定中檢查。",
        testConnection: "測試連線",
        testSuccess: "OpenAI 已回應。",
        testFailed: "OpenAI 沒有回應。",
        followUpHint: "Return 繼續提問。Esc 離開 Quick AI。",
        completeWithShiftTab: "Shift-Tab"
    )
}
